# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI (on push)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: bentoudev/python-build-workflow/.github/workflows/python-build.yml@main
    with:
      python-versions: >-
        ["3.7", "3.8", "3.9", "3.10", "3.11"]
